// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelFindDuplicates():Promise<void>;

export function DisplayFileDialog():Promise<Array<string>>;

export function FindDuplicates(arg1:Array<string>):Promise<void>;

export function MoveToTrash(arg1:Array<string>):Promise<Array<main.TrashResult>>;
