// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFindDuplicates() {
  return window['go']['main']['App']['CancelFindDuplicates']();
}

export function DisplayFileDialog() {
  return window['go']['main']['App']['DisplayFileDialog']();
}

export function FindDuplicates(arg1) {
  return window['go']['main']['App']['FindDuplicates'](arg1);
}

export function MoveToTrash(arg1) {
  return window['go']['main']['App']['MoveToTrash'](arg1);
}
